back_office:
    resource: "@BackOfficeBundle/Controller/"
    type:     annotation
    prefix:   /backoffice

crm:
    resource: "@CRMBundle/Controller/"
    type:     annotation
    prefix:   /crm

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix:   /