services:
#    crm.example:
#        class: CRMBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    crm.admin.customer:
        class: CRMBundle\Admin\CustomerAdmin
        arguments: [~, CRMBundle\Entity\Customer, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Customer }

    crm.admin.people:
        class: CRMBundle\Admin\PeopleAdmin
        arguments: [~, CRMBundle\Entity\People, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: People }
