services:
#    back_office.example:
#        class: BackOfficeBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    back_office.admin.config:
        class: BackOfficeBundle\Admin\ConfigAdmin
        arguments: [~, BackOfficeBundle\Entity\Config, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Config }
